package com.arash.arch

object Versions {
    const val arrow = "0.10.5"
    const val gradle = "4.1.3"
    const val kotlin = "1.4.32"
    const val coroutines = "1.4.1"
    const val gradleVersions = "0.39.0"
    const val arch = "2.3.1"
    const val archLifecycleExtensions = "2.2.0"
    const val archTest = "2.1.0"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.0"
    const val room = "2.3.0"
    const val dagger = "2.27"
    const val daggerAndroid = "2.25.4"
    const val okHttp = "4.9.0"
    const val gson = "2.8.6"
    const val retrofit = "2.9.0"
    const val stetho = "1.5.1"
    const val glide = "4.12.0"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val testRunner = "1.4.0"
    const val espresso = "3.4.0"
    const val mockitoKotlin = "1.6.0"
    const val navigationComponent = "2.3.5"
    const val retrofitCoroutines = "0.9.2"
    const val safeArgs = "2.3.5"
    const val shapeOfView = "1.4.7"
    const val arrowLegacySupport = "1.0.0"
    const val ratingBar = "1.0.5"
    const val exoPlayer = "2.12.0"
    const val hilt = "2.38.1"
    const val balloon = "1.2.3"
    const val canary = "2.7"
    const val persianDatePicker = "1.7.1"
    const val imageCropper = "2.5.1"
}